### ISSUE TITLE
Broken link 오류 관련

### ISSUE THREAD

**Issue by yklovett** [stkang/trss-feed#1]
YG_NAS <> [[Download Station] [YG_NAS] HTTP 다운로드 작업(null)에 실패했습니다] -> 
사용자님께
HTTP 다운로드 작업이 실패했습니다.
파일:
null
시간:
Fri Apr 12 20:44:49 2019
오류:
Broken Link
감사합니다.
Synology DiskStation

구성도 편하고 prefer 옵션덕에 너무 잘 사용중입니다 감사합니다

그런데 위에 메시지같이 broken link 라면서 다운로드를 못받을때가 가끔있습니다

어떤 파일인지를 모르니 그때마다 필터정리하고 전체를 다시받고있는데
어떤걸 받다가 실패했는지 제목이라도 확인할 방법이 있을까요?

**Comment by bbung224** [comment]
![image](https://user-images.githubusercontent.com/7835048/57448474-6cf17300-7294-11e9-894b-db1c0a4df6e4.png)
위 이미지의 url 을 [https://www.torrentzoa.com/torrent-tent-976310.html] 같은 형태로 맞추어 들어가시면 확인할 수 있습니다.

**Comment by yklovett** [comment]
사태가 사태이니만큼 close 하겠습니다 👍 
정말 난리네요 ㅎㅎ
