### ISSUE TITLE
tf broken link 관련

### ISSUE THREAD

**Issue by yklovett** [stkang/trss-feed#2]
염치없지만 stkang님 도커가 가장 깔끔한데
tf 사이트가 변경되었는지 모든 rss 가 안되서 이슈 남깁니다...

얼마전부터 일부 rss 가 broken link 이더니
오늘부터는 전부다 안됩니다... ㅠㅠ

혹시 시간되신다면 부탁드립니다

**Comment by bbung224** [comment]
따라 들어가보니 tf의 info.php 내용 중 magnet link쪽이 주석처리 되어 있네요

<div class="torrent_file">런닝맨.E450.190505.720p-NEXT.mp4.torrent </div><div class="torrent_magnet"></div><div class="torrent_list">런닝맨.E450.190505.720p-NEXT.mp4 (1.71GB)<br></div>

**Comment by yklovett** [comment]
@bbung224 음... 코딩은 무지해서 큰일이네요
그럼 이게 수정하기 어려운걸까요?

**Comment by bbung224** [comment]
@yklovett 대충 처리한다면 jsoup이 아닌 다른 library로 데이터 받아와서 주석구문만 제거하고 원래 로직에 태우면 될것같긴한데.. 자바는 해보질 않아서 ^^;

**Comment by stkang** [comment]
@yklovett @bbung224 
수정해서 Docker 다시 올렸습니다. 
이슈 너무 늦게 봐서 죄송합니다.

**Comment by yklovett** [comment]
@stkang 업으로 하시는것도 아닌데 죄송하시기는요...
항상 감사한 마음으로 사용중입니다.

**Comment by bbung224** [comment]
@yklovett 옳은 말씀입니다.
@stkang 유지해주시는것만해도 감사합니다
