### ISSUE TITLE
file.php만 다운로드 되는 현상

### ISSUE THREAD

**Issue by ktj1312** [stkang/trss-feed#7]
현재 다운로드하면 file.php 만 다운되고있습니다 아마 이번에 캡챠 업데이트 때매 그런 것 같은데 확인 가능할까요?

저만 이런가요?ㅎㅎ
파일에는 authentication failed만 있습니다
![캡처](https://user-images.githubusercontent.com/21598248/57633433-9127b980-75de-11e9-9dc8-502f63f0d80d.JPG)

**Comment by Eric-Jung2355** [comment]
저도 마찬가지 입니다. 확실하게 뚫는 방법이 필요합니다.

**Comment by ktj1312** [comment]
> 저도 마찬가지 입니다. 확실하게 뚫는 방법이 필요합니다.

티프리카 캡차 때문에 그런거 같은데 우회가 안된다면 다른 미러 사이트를 찾는게 빠를까요?

**Comment by ktj1312** [comment]
현재 정상적으로 동작합니다!

**Comment by JunhoYi** [comment]
전 이거 여전히 그러는데, TF 에서 검색을 하게 해둬서 그런걸까요? 혹시 검색 하는 url 패턴은 어떻게 쓰시는지 알수있을까요

**Comment by ktj1312** [comment]
> 전 이거 여전히 그러는데, TF 에서 검색을 하게 해둬서 그런걸까요? 혹시 검색 하는 url 패턴은 어떻게 쓰시는지 알수있을까요

http://localhost:88/rss/tf/feed?boards=tdrama&search=720p
현재 다음과 같이 검색을 하고 있습니다.

**Comment by JunhoYi** [comment]
@ktj1312 답변 감사합니다.
저는 바꿔도 HTTP 다운로드 작업(null)에 실패했습니다.가 나오네요 log한번 봐야겠네요 ㅠ

**Comment by stkang** [comment]
@ktj1312 @Eric-Jung2355 @JunhoYi 
https://rss.puns.kr 오픈합니다.

**Comment by ktj1312** [comment]
> @ktj1312 @Eric-Jung2355 @JunhoYi
> https://rss.puns.kr 오픈합니다.

감사합니다
